name: 'Branch Ops'
description: 'Operate on a branch and verify checks againt github'
inputs:
  github-token:
    description: 'Github Token with write permissions'
    required: true
  dest-branch:
    description: 'Branch to push to after commit'
    required: false
  force-push:
    description: 'Force push to the dest-branch. Use caution, can overwrite history'
    required: false
  verify-checks:
    description: ''
    required: false
  src-branch:
    description: 'Branch to pull from; defaults to current branch'
    required: false
  rebase:
    description: 'Pull and rebase branch before the commit, if branch does not exist this is a no-op'
    required: false
    default: 'false'
  commit-message:
    description: 'Provide commit message if you would like to commit'
    required: false
  files:
    description: 'Specific files to add before the commit.'
    required: false
    default: ''
  force-add-files:
    description: 'Force add files before commit, adds untracked files'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'

